### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by daveyjadams** [spatial-computing/CASPER#12]
Apologies if I've missed a step but it's the first time we've tried to install and use Casper.

I've tried installation using install.cmd but that file cannot find 2 dll's which the script thinks are in the Package folder but they are not in the download - EvcSolver64.dll and EvcSolver32.dll.

Any help would be greatly appreciated.

**Comment by kaveh096** [comment]
Sorry I missed your question on github. I know we already had this taken care of over email. I'll answer here as well for the sake of future users.

The two dlls are the casper dlls. One needs visual studio 2013 (or later), ArcGIS SDK, and some c++ experience to compile the source. If you compile the repo in 32bit mode, you'll get the EvcSolver32.dll. That being said normally compiling the source from scratch is not needed. Unless you want to change something in the code. You can always download the pre-compiled stable version from esri.com/arccasper.
